language: rust
rust:
- nightly
os:
- linux
script:
- cargo build --verbose
- cargo test --verbose
- cargo build --release --verbose
- cargo test --release --verbose
notifications:
  slack:
    secure: U1MJyiODZHG6wZYEZOaUx6yh/l4yiXzzEG+3ysilbGmeRK+vKq9tktBwqPDDYUdwwgdPCi55Yet1jpxpN+AQgEx0ihxjpzCSIWwv0bl72rd4y2fMxLddMAF6aKaqdMSPtPcldZwPOKTDYtvaOYwba0q9D4TUhqXm/9D7Zfk4IGs=
