[package]
name = "tomlenv"
version = "0.1.0"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]

[dependencies]
error-chain = "0.12.0"
serde = "1.0.70"
serde_derive = "1.0.70"
toml = "0.4.6"

[dev-dependencies]
getset = "0.0.6"
